---
#1 pre-installation
- name: Install pymongo for Ansible MongoDB module
  pip:
    name: pymongo

- name: Create /data/db directory for Mongod script
  file:
    path: /data/db
    state: directory
    mode: '0750'
    
- set_fact:
    mongodb_cmd_endstr: "{{mongodb_server_meta[mongodb_server].name}}"
    mongodb_url_endstr: "{{mongodb_server_meta[mongodb_server].url}}"
    mongodb_dns_endstr: "{{mongodb_server_meta[mongodb_server].dns}}"
    
#2 install by OS family    
- include: "{{ansible_os_family}}.yml"

#3 configure     
- block: 
  - name: Reload daemon-reload
    shell: systemctl daemon-reload
    
  - name: Restart MongoDB service
    service:
      name:  mongod
      state: started 

  - name: Setting MongoDB Administrator User
    mongodb_user:
      database: admin
      name: "{{mongodb_root_username}}"
      password: "{{mongodb_root_password}}"
      roles: 'root'
      state: present
      update_password: always
   
  - name: Enable MongoDB authorization
    blockinfile:
      path: /etc/mongod.conf
      insertafter: "#security:"
      block: |
        security:
          authorization: disabled
          
  when: mongodb_authentication

- block:
  - name: Enable MongoDB remote connection
    replace:
      path: /etc/mongod.conf
      regexp: 'bindIp: 127.0.0.1'
      replace: 'bindIp: 0.0.0.0'
      
  when: mongodb_remote
  
- name: Create extra database and user
  mongodb_user:
    login_user: root
    login_password: '{{mongodb_root_password}}'
    login_database: admin
    database: "{{ item.database_name }}"
    name: "{{ item.user_name }}"
    roles: "{{ item.roles }}"
    password: "{{ item.password | default('123456',true) }}"
  with_items: "{{ mongodb_users }}"
  when: (mongodb_users is defined) and (mongodb_users != none)

- name: Start and enable MongoDB service
  service:
    name:  mongod
    enabled: yes 
    state: started 
    
- name: Add soft link for Mongod directory
  shell: |
    ln -sf /etc/mongod.conf  /data/mongodb
    if [ -d "/var/lib/mongodb" ]; then ln -sf /var/lib/mongodb  /data/mongodb; fi
    if [ -d "/var/lib/mongo" ]; then ln -sf /var/lib/mongo  /data/mongodb; fi
    ln -sf /var/log/mongodb  /data/logs

#5 display version and service state of components
- name: Get MongoDB version
  shell: sudo sh -c "mongo --version | grep MongoDB  1>> /data/logs/install_version.txt" 

- name: Check MongoDB Service
  shell: systemctl status mongod | grep Active*
  register: check_mongodb_service
  notify: check_mongodb_service
